### PR TITLE
Random resize support for Yolo model training

### PR DESCRIPTION
**Pull request by umadevimcw**
@vera121 Added random resize of input for Yolo V2 and Yolo V3 model training by referring darknet implementation

### CODE REVIEW

**Comment by fanghuaqi** [comment]
@umadevimcw please fix the conflict file src/caffe/layers/base_data_layer.cpp
@vera121 maybe you can also take a look at it by click https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe/pull/9/conflicts.

**Comment by umadevimcw** [comment]
@vera121  @fanghuaqi  In base_data_layer.cpp https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe/blob/7aa1b205d45b19b180680413972d90b17e432528/src/caffe/layers/base_data_layer.cpp#L60 this line is needed for Yolo training, which is used by InternalThreadEntry() (https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe/pull/9/commits/5b80d69fc281e57c268a2b7fc7f2759c8ed2537d#diff-63622bcfad64cde48ae034c0ff70a249R60). This change created a conflict. We found that this line is commented out in Synopsys Caffe.

**Comment by vera121** [comment]
@umadevimcw I commented out that line since I saw it was not used in this LayerSetUp function afterwards, or in the CPU_ONLY mode after that at line 75.
If this is needed, could you check whether you miss that for the CPU_ONLY mode, and add it back? Then give me a new pull request.
Thanks.

**Comment by umadevimcw** [comment]
@vera121 top.size() is accessible in LayerSetUp function so we used the same for both modes. But we are unable to access the top.size in InternalThreadEntry() module (where we need size of the top), so we have added a variable called top_size_ which will updated in LayerSetup and used in the InternalThreadEntry() module.

**Comment by vera121** [comment]
@umadevimcw Thanks for the detailed explanations. I had a closer look at the code and understood it. I will fix it.

**Pull request merged**
